/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppsDropdown: typeof import('./src/components/common/header/AppsDropdown.vue')['default']
    BaseButton: typeof import('./src/components/ui/BaseButton.vue')['default']
    BaseDropdown: typeof import('./src/components/ui/BaseDropdown.vue')['default']
    BreadCrumb: typeof import('./src/components/common/BreadCrumb.vue')['default']
    EmailDropdown: typeof import('./src/components/common/header/EmailDropdown.vue')['default']
    HeaderLeftSide: typeof import('./src/components/layouts/header/HeaderLeftSide.vue')['default']
    HeaderRightSide: typeof import('./src/components/layouts/header/HeaderRightSide.vue')['default']
    LanguageDropdown: typeof import('./src/components/common/header/LanguageDropdown.vue')['default']
    LightDarkSwitchBtn: typeof import('./src/components/common/header/LightDarkSwitchBtn.vue')['default']
    LogoutContent: typeof import('./src/components/logout/LogoutContent.vue')['default']
    MainFooter: typeof import('./src/components/layouts/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/layouts/header/MainHeader.vue')['default']
    MainSidebar: typeof import('./src/components/layouts/MainSidebar.vue')['default']
    NotificationsDropdown: typeof import('./src/components/common/header/NotificationsDropdown.vue')['default']
    ProfileDropdown: typeof import('./src/components/common/header/ProfileDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarAccordion: typeof import('./src/components/common/sidebar/SidebarAccordion.vue')['default']
    SidebarHeader: typeof import('./src/components/common/sidebar/SidebarHeader.vue')['default']
    SidebarLink: typeof import('./src/components/common/sidebar/SidebarLink.vue')['default']
    SidebarMenu: typeof import('./src/components/common/sidebar/SidebarMenu.vue')['default']
    SidebarMenuItem: typeof import('./src/components/common/sidebar/SidebarMenuItem.vue')['default']
    SidebarSubTitle: typeof import('./src/components/common/sidebar/SidebarSubTitle.vue')['default']
  }
}
