/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppsDropdown: typeof import('./src/components/layouts/header/AppsDropdown.vue')['default']
    AverageDailySales: typeof import('./src/components/dashboard/AverageDailySales.vue')['default']
    BaseButton: typeof import('./src/components/ui/BaseButton.vue')['default']
    BaseDropdown: typeof import('./src/components/ui/BaseDropdown.vue')['default']
    BreadCrumb: typeof import('./src/components/common/BreadCrumb.vue')['default']
    EmailDropdown: typeof import('./src/components/layouts/header/EmailDropdown.vue')['default']
    ExpectedEarnings: typeof import('./src/components/dashboard/ExpectedEarnings.vue')['default']
    HeaderLeftSide: typeof import('./src/components/layouts/header/HeaderLeftSide.vue')['default']
    HeaderRightSide: typeof import('./src/components/layouts/header/HeaderRightSide.vue')['default']
    LanguageDropdown: typeof import('./src/components/layouts/header/LanguageDropdown.vue')['default']
    LightDarkSwitchBtn: typeof import('./src/components/layouts/header/LightDarkSwitchBtn.vue')['default']
    LogoutContent: typeof import('./src/components/logout/LogoutContent.vue')['default']
    MainFooter: typeof import('./src/components/layouts/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/layouts/header/MainHeader.vue')['default']
    MainSidebar: typeof import('./src/components/layouts/sidebar/MainSidebar.vue')['default']
    Newcustomer: typeof import('./src/components/dashboard/newcustomer.vue')['default']
    NewCustomersThisMonth: typeof import('./src/components/dashboard/NewCustomersThisMonth.vue')['default']
    'NewCustomersThisMonth.vue': typeof import('./src/components/dashboard/NewCustomersThisMonth.vue.vue')['default']
    NotificationsDropdown: typeof import('./src/components/layouts/header/NotificationsDropdown.vue')['default']
    ProductsOrders: typeof import('./src/components/dashboard/ProductsOrders.vue')['default']
    ProfileDropdown: typeof import('./src/components/layouts/header/ProfileDropdown.vue')['default']
    RevenueThisMonth: typeof import('./src/components/dashboard/RevenueThisMonth.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesByPOSLocation: typeof import('./src/components/dashboard/SalesByPOSLocation.vue')['default']
    SidebarAccordion: typeof import('./src/components/layouts/sidebar/SidebarAccordion.vue')['default']
    SidebarHeader: typeof import('./src/components/layouts/sidebar/SidebarHeader.vue')['default']
    SidebarLink: typeof import('./src/components/layouts/sidebar/SidebarLink.vue')['default']
    SidebarMenu: typeof import('./src/components/layouts/sidebar/SidebarMenu.vue')['default']
    SidebarMenuItem: typeof import('./src/components/layouts/sidebar/SidebarMenuItem.vue')['default']
    SidebarSubTitle: typeof import('./src/components/layouts/sidebar/SidebarSubTitle.vue')['default']
    StatsBoxes: typeof import('./src/components/dashboard/StatsBoxes.vue')['default']
    StockReport: typeof import('./src/components/dashboard/StockReport.vue')['default']
    TopSellingProducts: typeof import('./src/components/dashboard/TopSellingProducts.vue')['default']
    WebsiteVisitors: typeof import('./src/components/dashboard/WebsiteVisitors.vue')['default']
    WeeklySales: typeof import('./src/components/dashboard/WeeklySales.vue')['default']
    WhatHappening: typeof import('./src/components/dashboard/WhatHappening.vue')['default']
  }
}
